### ISSUE TITLE
visualize.plot_predictions should take in a label or an integer

### ISSUE THREAD

**Issue by bw4sz** [weecology/DeepForest-pytorch#40]
Right now it just takes an integer. We need a more general function that converts labels to integer if given. The integers are required for coloring scheme. Some thought needed on most intuitive way forward.

```
    plot_predictions(image=image, df=df)
Traceback (most recent call last):
  Debug Console, prompt 85, line 1
  File "/Users/benweinstein/opt/miniconda3/envs/DeepForest_pytorch/lib/python3.8/site-packages/deepforest/visualize.py", line 55, in plot_predictions
    color = label_to_color(row["label"])
  File "/Users/benweinstein/opt/miniconda3/envs/DeepForest_pytorch/lib/python3.8/site-packages/deepforest/visualize.py", line 109, in label_to_color
    return color_dict[label]
builtins.KeyError: 'Larch'
```

```
df.head()
     image_path  xmin  ymin  xmax  ymax  label
0  B10_0046.JPG    49    39   316   291  Larch
1  B10_0046.JPG   252    21   449   240  Larch
2  B10_0046.JPG   401    45   594   334  Larch
3  B10_0046.JPG   562    48   747   269  Larch
4  B10_0046.JPG   764     1   949   216  Larch
```

@dingyif , if interested.

**Comment by dingyif** [comment]
Definitely, I will work on this case. Thanks for the opportunity!
